In [2]:
# Using souvenir.csv as the base:

# Read in all of the other CSVs
# Replace the ID fields with the descriptions
# Save the new file to souvenirs.JSON
# Create separate CSV files for each owner's set of souvenirs.

In [3]:
# Read in all of the other CSVs

import pandas as pd
souvenir = pd.read_csv('souvenir.csv')
city = pd.read_csv('city.csv')
category = pd.read_csv('category.csv')
country = pd.read_csv('country.csv')
location = pd.read_csv('location.csv')
region = pd.read_csv('region.csv')
owner = pd.read_csv('owner.csv')

In [4]:
# Replace the ID fields with the descriptions
Master1 = souvenir.merge(city, how = 'outer', on = 'CityID')
Master1.rename(columns={"Name_x":"SouvenirName","Name_y":"CityName"},inplace=True )
Master2 = Master1.merge(category, how ='outer', on = 'CategoryID')
Master2.rename(columns ={"Name":"CategoryName"}, inplace = True)
Master3 = Master2.merge(location, how = "outer", on ="LocationID") 
Master4 = Master3.merge(owner, how = "outer", on = "OwnerID")
Master4.rename(columns={"Name":"Owner"}, inplace=True)
Souvenirs = Master4[['ItemID','ItemDescription','DateObtained','Price','Weight','SouvenirName','CityName','CategoryName','PlaceName','Latitude','Longitude','Owner']]
Souvenirs
#There is no countryID
#There are diff joins, just like SQL
#https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.merge.html
#souvenirs_with_categories.rename(columns={"Name_x":"SouvenirName","Name_y":"CategoryName"},inplace=True)

,ItemID,ItemDescription,DateObtained,Price,Weight,SouvenirName,CityName,CategoryName,PlaceName,Latitude,Longitude,Owner
0,1.0,NaN,2019/02/15,7.50,12.0,Grizzly Bear Mug,NaN,Kitchenware,Rocky Mountain National Park,40.343182,-105.688103,Group 3
1,2.0,NaN,2019/02/17,9.99,20.0,Snowy Mountain Mug,NaN,Kitchenware,Rocky Mountain National Park,40.343182,-105.688103,Group 3
2,12.0,NaN,2019/11/27,12.99,20.0,Mountain City Mug,NaN,Kitchenware,Rocky Mountain National Park,40.343182,-105.688103,Group 3
3,3.0,NaN,2019/03/05,12.99,16.0,Lobster Mug,NaN,Kitchenware,Offshore Trap/Pot Waters Area,38.000000,-82.000000,Group 3
4,4.0,NaN,2019/04/18,10.25,16.0,Sea Lion Mug,NaN,Kitchenware,Steller Sea Lion Protection Area,57.466667,-153.433334,Group 3
...,...,...,...,...,...,...,...,...,...,...,...,...
144,38.0,Exotic,2000/06/20,0.00,4.0,Palm Beach-sand,Ambondrona,Geological,NaN,NaN,NaN,Group 5
145,39.0,Better dirt than expected,2004/09/20,0.00,4.0,Parco delle fonti-dirt,Meldola,Geological,NaN,NaN,NaN,Group 5
146,40.0,Hints of nostalgia from the great days of the ...,2018/07/20,0.00,4.0,Park Lenina-dirt,Makaryev,Geological,NaN,NaN,NaN,Group 5
147,NaN,NaN,NaN,NaN,NaN,NaN,Ogden,NaN,NaN,NaN,NaN,NaN
148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Technology,NaN,NaN,NaN,NaN

In [5]:
# Save the new file to souvenirs.JSON
souvenirs = Souvenirs.to_json()
print(souvenirs)
# wikijson = wiki_airports.to_json()
# print(wikijson)

{"ItemID":{"0":1.0,"1":2.0,"2":12.0,"3":3.0,"4":4.0,"5":5.0,"6":20.0,"7":6.0,"8":7.0,"9":8.0,"10":9.0,"11":10.0,"12":17.0,"13":11.0,"14":19.0,"15":13.0,"16":14.0,"17":18.0,"18":15.0,"19":16.0,"20":98.0,"21":102.0,"22":99.0,"23":146.0,"24":121.0,"25":104.0,"26":105.0,"27":115.0,"28":118.0,"29":128.0,"30":138.0,"31":142.0,"32":111.0,"33":101.0,"34":134.0,"35":147.0,"36":133.0,"37":108.0,"38":107.0,"39":116.0,"40":119.0,"41":136.0,"42":141.0,"43":106.0,"44":144.0,"45":145.0,"46":112.0,"47":114.0,"48":117.0,"49":125.0,"50":129.0,"51":131.0,"52":140.0,"53":132.0,"54":100.0,"55":113.0,"56":120.0,"57":124.0,"58":127.0,"59":135.0,"60":139.0,"61":130.0,"62":109.0,"63":123.0,"64":103.0,"65":110.0,"66":122.0,"67":126.0,"68":137.0,"69":143.0,"70":59.0,"71":44.0,"72":49.0,"73":50.0,"74":48.0,"75":52.0,"76":66.0,"77":41.0,"78":62.0,"79":53.0,"80":56.0,"81":58.0,"82":57.0,"83":42.0,"84":47.0,"85":55.0,"86":64.0,"87":77.0,"88":78.0,"89":74.0,"90":75.0,"91":76.0,"92":45.0,"93":46.0,"94":54.0,"95":65.0,"96":68.0,"97":43.0,"98":51.0,"99":70.0,"100":61.0,"101":60.0,"102":63.0,"103":67.0,"104":69.0,"105":73.0,"106":71.0,"107":72.0,"108":95.0,"109":80.0,"110":94.0,"111":79.0,"112":90.0,"113":87.0,"114":97.0,"115":96.0,"116":86.0,"117":81.0,"118":82.0,"119":83.0,"120":93.0,"121":89.0,"122":85.0,"123":91.0,"124":84.0,"125":88.0,"126":92.0,"127":21.0,"128":22.0,"129":23.0,"130":24.0,"131":25.0,"132":26.0,"133":27.0,"134":28.0,"135":29.0,"136":30.0,"137":31.0,"138":32.0,"139":33.0,"140":34.0,"141":35.0,"142":36.0,"143":37.0,"144":38.0,"145":39.0,"146":40.0,"147":null,"148":null},"ItemDescription":{"0":null,"1":null,"2":null,"3":null,"4":null,"5":null,"6":null,"7":null,"8":null,"9":null,"10":null,"11":null,"12":null,"13":null,"14":null,"15":null,"16":null,"17":null,"18":null,"19":null,"20":"I got this because it was so weird that they sell Disney shotglasses! Does Mickey Mouse do shots?","21":"Yeah, sure, maybe it's basic.","22":"Does the Queen use this to stir her tea?","23":"Bought from an antique shop. Good for bashing rats","24":"Sometimes I fill this up with maple syrup to pour on my pancakes.... is that a disrespectful stereotype?","25":"It's heavy, but it's cool to drink out of!","26":"Why is it shaped like that? It looks so strange but so cool!","27":"My cousin bought this for me when I visited because she wouldn't stop roasting me for being a tourist.... it's ironic, I promise.","28":"They say they made this with the same methods that Ancient Romans used. It's that why it's so lopsided?","29":"Who knew they made special spoons for eating olives? Not me!","30":"He would be so proud.","31":"For portioning spices like sambal","32":"It's so dark, and so smooth!","33":"I found it on the beach, it's so nice and round!","34":"Wow, it's made from crystalized lava!","35":"I found one half of a large shell, walked a few meters, then found the other half and now keep them sitting next to each other","36":"Very helpful for my algebra homework!","37":"I think the top of the drum is made from papayrus, it sounds really awesome!","38":"It fits perfectly in the palm of my hand, and the stripes are so cute!","39":"The inside of the shell is iridescent, like a pearl. I wonder what this shell comes from.","40":"It's a little flute made of wood! The sound is deeper than I was expecting.","41":"A classic clamshell.","42":"It was really expensive and I don't know how to play it, but it's super cool.","43":"It really is a nice skyline","44":"I think the picture it too heavily photoshopped.","45":"Some impressionist art on a postcard from an Minneapolis artist.","46":"The view is so unbelievable... the sky really looked like that in person!","47":"They're so tall but so beautiful! I want to live in a city like this","48":"Who doesn't love a kangaroo? Aww....","49":"It was so beautiful to see the bridge all lit up for Christmas, I'll never forget it!","50":"Picture of the famous Patras Carnival, one of the biggest in all of Europe!","51":"A picture of the beautiful beach at Cannes!","52":"A picture of a neighborhood with shikumen architecture.","53":"Has \"I <3 Chicago\" on the front.","54":"The color is so intense, I love it!","55":"It's so beautiful, and the patterns were sewn by hand!","56":"I never wear it because I'm too afraid of damaging the beadwork, but it looks so elegant and expensive.","57":"These are honestly the best aviators I've ever worn. I'm gonna wear them until they break!","58":"It's so soft and light. It really helped to keep me cool while I was visiting.","59":"Now I have something to wear when my German inlaws invite me to Oktoberfest.","60":"Authentic and cozy, just what I always wanted","61":"An overview of the designs used in the old structures and buildings in Paris.","62":"These drawings were handmade! The ink strokes are so beautiful","63":"I'm going to learn how to make borsct! It's gonna happen!","64":"Someone made this by hand! It's so nice and it smells like leather.","65":"Don't judge me! I really like this one. The characters are cute AND deep.","66":"I love books with nature photographs... I didn't know moose (meese? mooses?) were so BIG!","67":"This was such an incredible read.","68":"A book about the life of one of Brazil's most iconic pop artists of the 20th century.","69":"I asked the bookstore clerk what they recommended and they gave me this.","70":"The Chef's favorite knife","71":"Cute shot glass from Key West Florida","72":"Video game bought on Steam","73":"Video game bought on Steam","74":"Started a squirt gun fight that ended the Cuban Missile Crisis","75":"Pokemon Card","76":"The prized jewel of France worn by Beyonce","77":"Common white quartz found in Utah","78":"Rarest and most expensive crystal","79":"Loot gained from besting pirates. ","80":"Rare green crystal","81":"Rare red crystal","82":"Orange crystal found at Utah's Topaz Mountain","83":"Bronze NYC ornament bought from visitors center","84":"9\/11 Memorial bronze ornament","85":"Taxidermy tazmanian devil","86":"They said it didn't exist","87":"Wrought-iron lattice tower","88":"Tallest mountain in the world","89":"Mural painting by Italian artist Leonardo da Vinci","90":"Portrait painting by Italian artist Leonardo da Vinci","91":"Limestone sculpure","92":"Sick T-Shirt from a wild PCB spring break back in '99","93":"Raise hell and praise Dale","94":"Blue Swim Suit from Toronto water park","95":"Helmet that provides elemental resistance","96":"The hat of Rasputin (from the song)","97":"Souvenir shop item commemorating the second ammendment.","98":"Pencil case with a panda hugging it. ","99":"Unbreakable lockpick","100":"Commemorative replica of the first President's fabled wooden teeth","101":"Rian Johnson's Creativity that he lost before he directed the Last Jedi","102":"Powerful shield belonging to the guard order of the town of Solitude","103":"Item invented by the Dwemer to store culture's knowledge","104":"Attack damage and critical strike","105":"A lot of attack damage. ","106":"Hitler's iconic mustache","107":"I stole this from Tom Hanks","108":null,"109":null,"110":null,"111":null,"112":null,"113":"      ","114":null,"115":null,"116":null,"117":null,"118":null,"119":null,"120":null,"121":null,"122":null,"123":null,"124":null,"125":null,"126":null,"127":"Very good dirt. Solid, reliable.","128":"Dry and depressing","129":"Tastes rich in Oxygen","130":"Unimagineable feeling between the toes","131":"High in phosphates","132":"There's something fishy in here, got sick after tasting it\u2026","133":"Very soft","134":"Smallest dirt on earth. Pathetic","135":"It's coarse. Gets everywhere. I don't like it","136":"Tastes like they have never won a war","137":"Very soft, great color","138":"Medium coarseness, tons of shells","139":"Looks very rich. I got a worm in here!","140":"BASIC","141":"Neat.","142":"Lots of critters and life. Kinda stinky","143":"Very Nice","144":"Exotic","145":"Better dirt than expected","146":"Hints of nostalgia from the great days of the USSR; however, a bit stale","147":null,"148":null},"DateObtained":{"0":"2019\/02\/15","1":"2019\/02\/17","2":"2019\/11\/27","3":"2019\/03\/05","4":"2019\/04\/18","5":"2019\/05\/07","6":"2021\/05\/08","7":"2019\/06\/15","8":"2019\/07\/21","9":"2019\/08\/01","10":"2019\/09\/15","11":"2019\/10\/15","12":"2021\/01\/11","13":"2019\/11\/09","14":"2021\/03\/26","15":"2019\/12\/04","16":"2020\/01\/15","17":"2021\/02\/28","18":"2020\/02\/13","19":"2020\/03\/15","20":"2021\/04\/02","21":"2005\/12\/17","22":"2020\/01\/05","23":"2005\/11\/15","24":"2004\/10\/27","25":"2013\/10\/30","26":"2012\/05\/24","27":"2019\/01\/18","28":"2001\/06\/06","29":"2006\/07\/08","30":"2021\/09\/21","31":"2005\/10\/17","32":"1995\/11\/04","33":"2001\/02\/15","34":"2014\/08\/13","35":"2001\/03\/30","36":"1998\/08\/19","37":"2012\/06\/28","38":"2021\/01\/08","39":"2018\/03\/25","40":"2002\/10\/19","41":"2000\/04\/19","42":"2001\/01\/25","43":"2015\/07\/15","44":"2018\/07\/02","45":"2003\/09\/06","46":"2007\/08\/01","47":"2011\/04\/05","48":"2017\/02\/23","49":"2013\/12\/25","50":"2016\/04\/15","51":"2014\/11\/11","52":"2020\/09\/10","53":"2000\/01\/01","54":"1998\/06\/12","55":"2014\/06\/14","56":"2003\/09\/12","57":"2021\/01\/18","58":"2011\/06\/16","59":"1997\/02\/26","60":"2016\/10\/10","61":"2015\/04\/28","62":"2007\/12\/30","63":"2005\/12\/13","64":"1999\/11\/23","65":"2010\/01\/05","66":"2008\/05\/15","67":"1999\/12\/31","68":"2005\/09\/01","69":"2004\/11\/22","70":"1998\/07\/11","71":"2020\/12\/25","72":"2019\/07\/20","73":"2019\/05\/01","74":"1962\/08\/20","75":"2010\/06\/10","76":"2009\/03\/30","77":"2020\/06\/01","78":"2011\/07\/11","79":"2008\/08\/07","80":"2011\/08\/15","81":"1937\/02\/25","82":"1982\/03\/11","83":"2019\/12\/30","84":"2020\/03\/14","85":"2000\/06\/13","86":"2021\/02\/26","87":"1887\/01\/28","88":"2003\/02\/14","89":"1490\/04\/17","90":"1507\/05\/20","91":"2020\/09\/12","92":"1999\/04\/27","93":"2008\/02\/05","94":"2019\/01\/01","95":"2010\/06\/23","96":"2011\/11\/11","97":"2021\/01\/02","98":"2014\/07\/01","99":"2012\/10\/30","100":"2003\/03\/03","101":"2016\/05\/20","102":"2014\/05\/19","103":"2011\/07\/12","104":"2021\/05\/18","105":"2021\/05\/18","106":"1940\/04\/30","107":"2000\/06\/14","108":"2007\/07\/07","109":"2008\/06\/18","110":"2016\/07\/04","111":"2007\/01\/10","112":"2002\/08\/03","113":"2015\/05\/08","114":"2021\/12\/25","115":"2021\/05\/18","116":"2018\/05\/18","117":"2019\/12\/23","118":"2020\/12\/02","119":"2020\/12\/02","120":"1999\/12\/24","121":"2018\/05\/18","122":"2016\/05\/15","123":"2020\/08\/05","124":"2013\/08\/23","125":"2000\/01\/01","126":"2016\/09\/23","127":"2007\/03\/21","128":"2009\/08\/01","129":"2010\/03\/11","130":"2015\/12\/25","131":"2018\/04\/22","132":"2019\/09\/28","133":"2020\/06\/12","134":"2020\/08\/20","135":"2020\/09\/20","136":"2021\/02\/20","137":"2021\/07\/20","138":"2021\/12\/20","139":"2021\/02\/20","140":"2021\/01\/20","141":"2021\/03\/20","142":"2017\/08\/20","143":"2014\/01\/20","144":"2000\/06\/20","145":"2004\/09\/20","146":"2018\/07\/20","147":null,"148":null},"Price":{"0":7.5,"1":9.99,"2":12.99,"3":12.99,"4":10.25,"5":6.91,"6":25.0,"7":8.99,"8":9.75,"9":13.25,"10":11.4,"11":19.99,"12":15.0,"13":14.25,"14":9.95,"15":12.5,"16":11.99,"17":12.25,"18":10.75,"19":10.99,"20":25.99,"21":14.99,"22":50.0,"23":17.99,"24":9.5,"25":17.99,"26":12.99,"27":12.99,"28":22.99,"29":22.25,"30":12.29,"31":6.0,"32":0.0,"33":0.0,"34":18.99,"35":0.0,"36":99.99,"37":60.0,"38":0.0,"39":0.0,"40":45.5,"41":0.0,"42":1640.0,"43":2.99,"44":2.99,"45":5.99,"46":1.0,"47":0.8,"48":1.2,"49":1.25,"50":0.99,"51":1.99,"52":2.5,"53":12.99,"54":45.0,"55":120.0,"56":60.0,"57":14.99,"58":35.99,"59":69.99,"60":42.0,"61":49.99,"62":29.99,"63":15.6,"64":35.0,"65":15.99,"66":17.99,"67":14.69,"68":16.49,"69":1.34,"70":0.0,"71":0.0,"72":0.0,"73":0.0,"74":0.0,"75":0.0,"76":0.0,"77":0.0,"78":0.0,"79":0.0,"80":0.0,"81":0.0,"82":0.0,"83":0.0,"84":0.0,"85":0.0,"86":0.0,"87":0.0,"88":0.0,"89":0.0,"90":0.0,"91":0.0,"92":0.0,"93":0.0,"94":0.0,"95":0.0,"96":0.0,"97":0.0,"98":0.0,"99":0.0,"100":0.0,"101":0.0,"102":0.0,"103":0.0,"104":0.0,"105":0.0,"106":0.0,"107":0.0,"108":8.95,"109":20.8,"110":2.0,"111":15.0,"112":49.99,"113":22.95,"114":1800000.0,"115":41.16,"116":22.0,"117":29.95,"118":50.0,"119":40.0,"120":35.99,"121":10.0,"122":15.0,"123":20.0,"124":25.0,"125":9.99,"126":19.99,"127":0.0,"128":0.0,"129":0.0,"130":0.0,"131":0.0,"132":0.0,"133":0.0,"134":0.0,"135":0.0,"136":0.0,"137":0.0,"138":0.0,"139":0.0,"140":0.0,"141":0.0,"142":0.0,"143":0.0,"144":0.0,"145":0.0,"146":0.0,"147":null,"148":null},"Weight":{"0":12.0,"1":20.0,"2":20.0,"3":16.0,"4":16.0,"5":20.0,"6":24.0,"7":12.0,"8":16.0,"9":24.0,"10":20.0,"11":12.0,"12":12.0,"13":16.0,"14":16.0,"15":12.0,"16":20.0,"17":20.0,"18":16.0,"19":12.0,"20":2.5,"21":2.0,"22":4.0,"23":12.0,"24":4.0,"25":5.0,"26":6.0,"27":3.0,"28":3.0,"29":6.0,"30":2.0,"31":3.0,"32":5.0,"33":4.0,"34":12.0,"35":16.0,"36":8.0,"37":34.0,"38":1.5,"39":2.0,"40":15.0,"41":3.5,"42":36.0,"43":1.0,"44":1.0,"45":1.0,"46":0.75,"47":1.0,"48":1.0,"49":1.0,"50":1.0,"51":1.0,"52":1.0,"53":5.0,"54":8.0,"55":86.0,"56":5.0,"57":6.0,"58":7.0,"59":10.0,"60":24.0,"61":20.0,"62":18.0,"63":17.0,"64":20.0,"65":21.0,"66":19.0,"67":22.0,"68":9.0,"69":5.0,"70":null,"71":null,"72":null,"73":null,"74":null,"75":null,"76":null,"77":null,"78":null,"79":null,"80":null,"81":null,"82":null,"83":null,"84":null,"85":null,"86":null,"87":null,"88":null,"89":null,"90":null,"91":null,"92":null,"93":null,"94":null,"95":null,"96":null,"97":null,"98":null,"99":null,"100":null,"101":null,"102":null,"103":null,"104":null,"105":null,"106":null,"107":null,"108":4.2,"109":19.36,"110":1.0,"111":6.7,"112":20.0,"113":10.0,"114":17637.0,"115":8.47,"116":8.0,"117":13.4,"118":5.0,"119":10.0,"120":15.0,"121":6.0,"122":6.88,"123":18.0,"124":5.0,"125":5.0,"126":5.0,"127":4.0,"128":4.0,"129":4.0,"130":4.0,"131":4.0,"132":4.0,"133":4.0,"134":4.0,"135":4.0,"136":4.0,"137":4.0,"138":4.0,"139":4.0,"140":4.0,"141":4.0,"142":4.0,"143":4.0,"144":4.0,"145":4.0,"146":4.0,"147":null,"148":null},"SouvenirName":{"0":"Grizzly Bear Mug","1":"Snowy Mountain Mug","2":"Mountain City Mug","3":"Lobster Mug","4":"Sea Lion Mug","5":"Coral Reef Mug","6":"Pink Mug","7":"Ocean Life Mug","8":"Landscape Mug","9":"Bird Mug","10":"Dunes Mug","11":"Skier Mug","12":"Cowboy Mug","13":"Desert Mug","14":"Gila Monster Mug","15":"Joshua Tree Mug","16":"River View Mug","17":"Buffalo Mug","18":"Hot Springs Mug","19":"Cave Bat Mug","20":"Mickey Mouse Shotglass","21":"Eiffel Tower Shotglass","22":"Gold Spoon","23":"Old Pewter Spoon","24":"Maple Leaf Shotglass","25":"Stone Shotglass","26":"Weird spoon","27":"Union Jack Shotglass","28":"Ancient Roman Spoon","29":"Olive Spoon","30":"Cristo Redentor Shotglass","31":"Small Wooden Spoon","32":"Black Rock","33":"Smooth Rock","34":"Obsidian","35":"Chiton Shell","36":"TI-89","37":"Egyptian Drum","38":"Red scallop shell","39":"Shiny Shell","40":"Zuffolo","41":"Clamshell","42":"Shamisen","43":"City postcard","44":"Beach Postcard","45":"Minneapolis Institute of Art Postcard","46":"Sunset Postcard","47":"Petronas Towers Postcard","48":"Kangaroo Postcard","49":"Story Bridge","50":"Carnival Postcard","51":"Beach Postcard","52":"Shikumen Postcard","53":"Tourist Shirt","54":"Fancy Scarf","55":"Sari","56":"Blouse","57":"Sunglasses","58":"Headscarf","59":"Dirndl","60":"Poncho","61":"Architecture Book","62":"Ink Artbook","63":"Cookbook","64":"Hand-bound sketchbook","65":"Manga","66":"Moose Photographs","67":"Long Walk to Freedom","68":"Jorge Ben Jor Autobiography","69":"Like Water for Chocolate","70":"Gordon Ramsey's Filet Knife","71":"I Got Tipsy In Key West shot glass","72":"Oxygen Not Included","73":"Stardew Valley","74":"Super Soaker","75":"Shiny Limited Edition Charzard","76":"The Pink Panther","77":"Quartz rock","78":"Red Beryl","79":"Diamonds","80":"Emerald","81":"Ruby","82":"Topaz","83":"NYC bronze ornament","84":"9\/11 bronze ornament","85":"Taxidermy Tazmanian Devil","86":"LoL Player's Sanity","87":"Eiffle Tower Postcard","88":"Mount Everest Postcard","89":"The Last Supper","90":"Mona Lisa","91":"Sphinx","92":"PCB T-Shirt","93":"Daytona 500 Hat","94":"Swim Suit","95":"Ancient Helmet of the Unburned","96":"Rasputin's Hat","97":"Texas Pen","98":"Panda Pencil Holder","99":"Skeleton Key","100":"Replica George Washington Wood Teeth","101":"Rian Johnson's Creativity","102":"Shield of Solitude","103":"Dwemer Lexicon","104":"Infinity Edge ","105":"BF Sword","106":"Hitler's Mustache","107":"Da Vinci's Code","108":"Shot Glass","109":"12'' Ancient Traditional Korea Hanbok Doll","110":"American Flag","111":"Tenugui Cotton Cloth Rice Grains","112":"Alpaca Poncho","113":"Organic Maple Syrup","114":"80\" Rare 100% Purple Natural Emerald Jadeite Jade Dragon","115":"Vintage Maori Carving Intricate Patu Club & Long House Box Polynesian Art","116":"Cast Iron Door Stop","117":"Resort Snowglobe","118":"Iron Standing Dog","119":"Crafts Enameled Cockatoo","120":"Decorative African Wood Mask ","121":"Metal Jewelry Box","122":"Hand Painted Enameled Telephone","123":"Classic Vintage Antique Heart Shape Jewelry Box","124":"Hand Painted Rose Flower","125":"Eiffel Tower Model","126":"Chicago Cubs T-Shirt","127":"Central Park-dirt","128":"Hollywood Bowl-dirt","129":"Burham Park-dirt","130":"Playa Tortugas-sand","131":"Bukhansan National Park-dirt","132":"Wuhan Institute of Virology-dirt","133":"TEL AVIV BEACH-sand","134":"Bourscheid Neige Luges-dirt","135":"Lagoon Beach-sand","136":"Champ de Mars-dirt","137":"Playa del Carmen-sand","138":"Playa Punta Esmeralda-sand","139":"Hyde Park-dirt","140":"National Park-dirt","141":"Promenade des Anglais-sand","142":"Hikkaduwa Beach-sand","143":"Al Bustan Beach-sand","144":"Palm Beach-sand","145":"Parco delle fonti-dirt","146":"Park Lenina-dirt","147":null,"148":null},"CityName":{"0":null,"1":null,"2":null,"3":null,"4":null,"5":null,"6":null,"7":null,"8":null,"9":null,"10":null,"11":null,"12":null,"13":null,"14":null,"15":null,"16":null,"17":null,"18":null,"19":null,"20":"New York City","21":"Paris","22":"London","23":"London","24":"Toronto","25":"Copenhagen","26":"Helsinki","27":"Liverpool","28":"Rome","29":"Athens","30":"Rio de Janeiro","31":"Surabaya","32":"Seoul","33":"Barcelona","34":"Aberdeen","35":"Nice","36":"Dallas","37":"Cairo","38":"Miami","39":"Perth","40":"Venice","41":"Madrid","42":"Kyoto","43":"Los Angeles","44":"Cancun","45":"Minneapolis","46":"Bangkok","47":"Kuala Lumpur","48":"Auckland","49":"Brisbane","50":"Patras","51":"Cannes","52":"Shanghai","53":"Chicago","54":"Munich","55":"Mumbai","56":"Naples","57":"Edinburgh","58":"Casablanca","59":"Frankfurt","60":"Buenos Aires","61":"Paris","62":"Beijing","63":"Moscow","64":"Sydney","65":"Tokyo","66":"Montreal","67":"Johannesburg","68":"Rio de Janeiro","69":"Mexico City","70":"London","71":"Key West","72":null,"73":null,"74":"Havana","75":"Minneapolis","76":"Paris","77":"Beaver","78":"Beaver","79":"Babati","80":"Babati","81":"Babati","82":"Topaz Mountain","83":"New York City","84":"Washington DC","85":"Babati","86":"Milwaukee","87":"Paris","88":"Qing Zang Gaoyuan","89":"Milan","90":"Florence","91":"Cairo","92":"Panama City Beach","93":"Daytona Beach","94":"Toronto","95":"Labyrinthian","96":"Moscow","97":"Dallas","98":"Beijing","99":"Thieves' Guild","100":"Washington DC","101":"Hollywood","102":"Solitude","103":"Riften Docks","104":"The Fountain","105":"The Fountain","106":"Hamburg","107":"Vatican City","108":"Berlin","109":"Seoul","110":"Washington DC","111":"Niigata","112":"Melbourne","113":"Paris","114":"Beijing","115":"Melbourne","116":"Toronto","117":"Orlando","118":"New Delhi","119":"Atlanta","120":"Chicago","121":"Washington DC","122":"Warsaw","123":"Nairobi","124":"Manchester","125":"Lima","126":"Beijing","127":"New York City","128":"Los Angeles","129":"Chicago","130":"Cancun","131":"Seoul","132":"Wuhan","133":"Tel Aviv","134":"Luxembourg","135":"Cape Town","136":"Paris","137":"Playa del Carmen","138":"Playa del Carmen","139":"London","140":"Nice","141

In [8]:
Souvenirs[['Price','Weight']].describe()

              Price        Weight
count  1.470000e+02    109.000000
mean   1.226800e+04    171.754679
std    1.484596e+05   1688.389720
min    0.000000e+00      0.750000
25%    0.000000e+00      4.000000
50%    2.990000e+00      6.000000
75%    1.624000e+01     16.000000
max    1.800000e+06  17637.000000

In [9]:
Souvenirs.agg({'Price':['min','max','median','sum'],'Weight':['min','max','median']})

             Price    Weight
min           0.00      0.75
max     1800000.00  17637.00
median        2.99      6.00
sum     1803395.65       NaN

In [10]:
Souvenirs.groupby('CategoryName')['Price'].sum() #could .xx() anything on describe list!

CategoryName
Art                  155.98
Artifact         1800041.16
Book                 197.08
Clothing             485.94
Food                  22.95
Geological            18.99
Kitchenware          481.61
Miscellaneous       1949.44
Postcard              21.70
Technology             0.00
Tool                   0.00
Toy                   20.80
Name: Price, dtype: float64

In [11]:
Souvenirs.groupby('CategoryName')['Price'].describe()

,count,mean,std,min,25%,50%,75%,max
CategoryName,,,,,,,,
Art,10.0,15.598000,14.575871,0.00,2.4975,12.500,23.7500,40.00
Artifact,10.0,180004.116000,569208.532762,0.00,0.0000,0.000,0.0000,1800000.00
Book,9.0,21.897778,14.230154,1.34,15.6000,16.490,29.9900,49.99
Clothing,16.0,30.371250,33.407899,0.00,0.0000,17.495,46.2475,120.00
Food,1.0,22.950000,NaN,22.95,22.9500,22.950,22.9500,22.95
Geological,30.0,0.633000,3.467084,0.00,0.0000,0.000,0.0000,18.99
Kitchenware,35.0,13.760286,8.582943,0.00,9.8500,12.290,14.9950,50.00
Miscellaneous,16.0,121.840000,405.925566,0.00,0.0000,1.000,46.6250,1640.00
Postcard,12.0,1.808333,1.661110,0.00,0.9425,1.225,2.6225,5.99
Technology,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Tool,3.0,0.000000,0.000000,0.00,0.0000,0.000,0.0000,0.00
Toy,5.0,4.160000,9.302043,0.00,0.0000,0.000,0.0000,20.80

In [13]:
Souvenirs.groupby(['CategoryName','Owner'])['Price'].median() ##can agg on multiple columns

CategoryName   Owner
Art            Group 1        20.000
               Group 4         0.000
Artifact       Group 1    900020.580
               Group 4         0.000
Book           Group 2        16.490
Clothing       Group 1        19.990
               Group 2        43.500
               Group 4         0.000
Food           Group 1        22.950
Geological     Group 2         0.000
               Group 4         0.000
               Group 5         0.000
Kitchenware    Group 1         8.950
               Group 2        16.490
               Group 3        11.695
               Group 4         0.000
Miscellaneous  Group 1        25.975
               Group 2        22.750
               Group 4         0.000
Postcard       Group 2         1.620
               Group 4         0.000
Tool           Group 4         0.000
Toy            Group 1        20.800
               Group 4         0.000
Name: Price, dtype: float64

In [14]:
Souvenirs.groupby(['Owner','CategoryName']).agg({'SouvenirName':list}) # can agg w/ string values!

                                                            SouvenirName
Owner   CategoryName
Group 1 Art            [Crafts Enameled Cockatoo, Decorative African ...
        Artifact       [80" Rare 100% Purple Natural Emerald Jadeite ...
        Clothing       [Tenugui Cotton Cloth Rice Grains, Alpaca Ponc...
        Food                                       [Organic Maple Syrup]
        Kitchenware                                         [Shot Glass]
        Miscellaneous  [American Flag, Cast Iron Door Stop, Resort Sn...
        Toy                 [12'' Ancient Traditional Korea Hanbok Doll]
Group 2 Book           [Architecture Book, Ink Artbook, Cookbook, Han...
        Clothing       [Tourist Shirt, Fancy Scarf, Sari, Blouse, Sun...
        Geological                   [Black Rock, Smooth Rock, Obsidian]
        Kitchenware    [Mickey Mouse Shotglass, Eiffel Tower Shotglas...
        Miscellaneous  [Chiton Shell, TI-89, Egyptian Drum, Red scall...
        Postcard       [City postcard, Beach Postcard, Minneapolis In...
Group 3 Kitchenware    [Grizzly Bear Mug, Snowy Mountain Mug, Mountai...
Group 4 Art                         [The Last Supper, Mona Lisa, Sphinx]
        Artifact       [Replica George Washington Wood Teeth, Rian Jo...
        Clothing       [PCB T-Shirt, Daytona 500 Hat, Swim Suit, Anci...
        Geological     [The Pink Panther, Quartz rock, Red Beryl, Dia...
        Kitchenware    [Gordon Ramsey's Filet Knife, I Got Tipsy In K...
        Miscellaneous  [NYC bronze ornament, 9/11 bronze ornament, Ta...
        Postcard         [Eiffle Tower Postcard, Mount Everest Postcard]
        Tool              [Texas Pen, Panda Pencil Holder, Skeleton Key]
        Toy            [Oxygen Not Included, Stardew Valley, Super So...
Group 5 Geological     [Central Park-dirt, Hollywood Bowl-dirt, Burha...

In [15]:
bills = Souvenirs[['Owner','CategoryName','Price']]

def calc_tips_10percent(x):
    return (x * .1)

bills['tip'] = bills.Price.apply(calc_tips_10percent)
bills['final_total'] = bills['Price'] + bills['tip']
bills.head()

C:\Users\Stephanie Leiva\AppData\Local\Temp\ipykernel_10200\2717004328.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bills['tip'] = bills.Price.apply(calc_tips_10percent)
C:\Users\Stephanie Leiva\AppData\Local\Temp\ipykernel_10200\2717004328.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bills['final_total'] = bills['Price'] + bills['tip']

     Owner CategoryName  Price    tip  final_total
0  Group 3  Kitchenware   7.50  0.750        8.250
1  Group 3  Kitchenware   9.99  0.999       10.989
2  Group 3  Kitchenware  12.99  1.299       14.289
3  Group 3  Kitchenware  12.99  1.299       14.289
4  Group 3  Kitchenware  10.25  1.025       11.275

In [16]:
bills = Souvenirs[['Owner','CategoryName','Price']]
bills.head()

def calc_tips_percent(total,percentage):
    return (total * percentage/100)

bills['tip'] = bills.Price.apply(calc_tips_percent,percentage=10)
bills['final_total'] = bills['Price'] + bills['tip']
bills.head()

C:\Users\Stephanie Leiva\AppData\Local\Temp\ipykernel_10200\2951204345.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bills['tip'] = bills.Price.apply(calc_tips_percent,percentage=10)
C:\Users\Stephanie Leiva\AppData\Local\Temp\ipykernel_10200\2951204345.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  bills['final_total'] = bills['Price'] + bills['tip']

     Owner CategoryName  Price    tip  final_total
0  Group 3  Kitchenware   7.50  0.750        8.250
1  Group 3  Kitchenware   9.99  0.999       10.989
2  Group 3  Kitchenware  12.99  1.299       14.289
3  Group 3  Kitchenware  12.99  1.299       14.289
4  Group 3  Kitchenware  10.25  1.025       11.275